services:
  python_app:
    build: .
    expose:
      - "8001"
    ports:
      - "8001:8001"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - .:/app  # Mount local directory to /app inside the container, optional
#    networks:
#      dnet:

#networks:  
#  dnet:  
#    driver: bridge  
    # redis:
      # image: "redis:alpine"
